simplesocial/accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views
from simplesocial import settings

app_name = 'accounts'

urlpatterns = [
    path("login", auth_views.LoginView.as_view(template_name = 'accounts/login.html'), name = 'login'),
    path("signup", views.SignUp.as_view(), name = 'signup'),
    path("logout", auth_views.LogoutView.as_view(next_page=settings.LOGOUT_REDIRECT_URL), name = 'logout'),
]

simplesocial/simplesocial/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name = "home"),
    path('accounts/', include('accounts.urls',namespace = "accounts")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('test/', views.TestPage.as_view(), name='test'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
]

simplesocial/accounts/models.py
from django.db import models
from django.contrib import auth

# Create your models here.
class User(auth.models.User, auth.models.PermissionsMixin):
    
    def __str__(self):
        return "@{}".format(self.username)
    

simplesocial/accounts/forms.py
from typing import Any
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class UserCreateform(UserCreationForm):

    class Meta:
        fields = ['username', 'email', 'password1', 'password2']
        model = get_user_model()

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Display Name'
        self.fields['email'].label = 'Email Address'

simplesocial/accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView

from . import forms
# Create your views here.

class SignUp(CreateView):
    form_class = forms.UserCreateform
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

simplesocial/simplesocial/views.py
from django.views.generic import TemplateView

class TestPage(TemplateView):
    template_name = 'test.html'

class ThanksPage(TemplateView):
    template_name = 'thanks.html'

class HomePage(TemplateView):
    template_name = 'index.html'

simplesocial/accounts/templates/accounts/login.html
{% extends "base.html" %}

{% load django_bootstrap5 %}

{% block mycontent %}
<div class="container">
    <h1>Login</h1>
    <form method = "POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type = "submit" class = 'btn btn-default' value = "Login"> 
    </form>
{% endblock %}
</div>

simplesocial/accounts/templates/accounts/signup.html
{% extends "base.html" %}

{% load django_bootstrap5 %}

{% block content %}
<div class="container">
    <h1>Sign Up </h1>
    <form method = "POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type = "submit" class = 'btn btn-default' value = "Sign Up"> 
    </form>
{% endblock %}
</div>

simplesocial/templates/base.html
<!DOCTYPE html>
{% load static %}
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Star Social</title>

        <!-- css bootstrap 5 https://getbootstrap.com/docs/5.3/getting-started/introduction/#separate-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">


        <!-- js : jquery cdn link-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
        
        <!-- google font api-->
        <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>

        <!-- link css created-->
        <link rel="stylesheet" href="{% static 'simplesocial/css/master.css'%}">

        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>

        <nav class='navbar mynav' role='navigation' id='navbar'>
            <div class='container'>
                <a class='navbar-brand mynav' href="{% url 'home' %}">Start Social </a>

                <ul class='nav navbar-nav navbar-right'>
                    {% if user.is_authenticated %}
                        <li><a href="#">Post</a></li>
                        <li><a href="#">Groups</a></li>
                        <li><a href="#">Create Group</a></li>
                        {% comment %} <li><a href="{% url 'accounts:logout' %}">Log Out</a></li>  cannot use a herf for log out{% endcomment %}
                        <form method="post" action="{% url 'logout' %}">
                            {% csrf_token %}
                            <button type="submit">Log Out</button>
                        </form>
                    {% else %}
                        <li><a href="#">Groups</a></li>
                        <li><a href="{% url 'accounts:login' %}">Log In</a></li>
                        <li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>

        <div class="container mycontent">
            {% block content %}

            {% endblock %}
        </div>

        <script src="" async defer></script>
    </body>
</html>

simplesocial/templates/index.html
{% extends "base.html" %}

{% block content %}
    <h1> Welcome </h1>
{% endblock  %}

simplesocial/templates/test.html
{% extends "base.html" %}
{% block content %}
    <h1> You are logged in </h1>
{% endblock  %}
    

simplesocial/templates/thanks.html
{% extends "base.html" %}
{% block content  %}
    <h1> Thanks for visitting </h1>
{% endblock  %}